name: Deploy Github Docs

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  deploy-github-pages:
    name: Deploy docs to GitHub pages
    runs-on: ubuntu-latest
    if: github.repository == 'release-jf/full'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: pnpm

      - name: Docs build
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run build
          > docs/.vuepress/dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: release-jf/release-jf.github.io
          branch: gh-pages
          folder: docs/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
