name: Main Action

on:
  push:
    branches:
      - "**"
    tags:
      - v**
  pull_request:
    branches:
      - main

jobs:
 # release-please:
  #  name: release-please
 #   if: github.ref_name == 'main'
 #   uses: ./.github/workflows/release-please.yml
 #   secrets:
  #    RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    
 # automerge:
 #   name: automerge
 #   if: github.ref_name == 'main'
 #   needs:
  #    - release-please
 #   uses: ./.github/workflows/automerge.yml
  #  secrets:
   #   RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    
  build-project:
    name: Build Project
   # needs:
    #  - release-please
    #  - automerge
    uses: ./.github/workflows/build-project.yml

  deploy-github-docs:
    name: Deploy GitHub Docs
    # Only triggered on main or work branch
    if: github.ref_name == 'main'
    needs:
      - build-project
    uses: ./.github/workflows/deploy-github-docs.yml
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

 # publish-packages:
 #   name: Publish Packages
    # Only triggered by v2 tag push
  #  if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
 #   needs:
  #    - build-project
 #   uses: ./.github/workflows/publish.yml
  #  secrets:
   #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
